tap "brewforge/chinese", trusted: true
tap "homebrew/services"
tap "iohannrabeson/tap", "https://github.com/IohannRabeson/homebrew-tap"
tap "laishulu/homebrew", trusted: true
tap "louisbrunner/valgrind", trusted: true
tap "nikitabobko/tap", trusted: true
tap "rami3l/tap", trusted: true
tap "syhily/git-gc", trusted: true
tap "thedavidweng/unsigned-tap"
# Easily generate Instruments traces for your rust crate
brew "cargo-instruments"
# Distributed revision control system
brew "git"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Minimalist GNU for Windows and GCC cross-compilers
brew "mingw-w64"
# Sliding, tiling window manager for MacOS
brew "paneru"
# Hook preloader
brew "proxychains-ng"
# Makes Time Machine respect .gitignore files
brew "iohannrabeson/tap/tmignore-rs", trusted: true
# An input source switching daemon for macOS.
brew "rami3l/tap/clavy", args: ["HEAD"]
# Pacman-like syntax wrapper for many package managers.
brew "rami3l/tap/pacaptr", args: ["HEAD"]
# Android SDK component
cask "android-platform-tools"
# Display management tool
cask "betterdisplay"
# Tool to customise input devices and automate computer systems
cask "bettertouchtool"
# Rule based proxy base on Clash
cask "brewforge/chinese/clashx-meta"
# Server and cloud storage browser
cask "cyberduck"
# Advanced Dock preferences
cask "dockey"
# Matrix collaboration client
cask "element"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Tools to protect your emails and files
cask "gpg-suite"
# Free and open-source media player
cask "iina"
# Keyboard customiser
cask "karabiner-elements"
# File archiver
cask "keka"
# Free and open-source media player
cask "kodi"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Open-source download manager
cask "motrix"
# Mounts servers and cloud storages as a disk on the desktop
cask "mountain-duck"
# Re-mounts write-protected NTFS volumes
cask "mounty"
# Free and open-source RSS reader
cask "netnewswire"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Android file transfer
cask "openmtp"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
# Colour picker for colours onscreen
cask "pika"
# Browse, manage, inspect containers and images
cask "podman-desktop"
# Peer to peer Bitorrent client
cask "thedavidweng/unsigned-tap/qbittorrent", trusted: true
# HTTP client that helps testing and describing APIs
cask "rapidapi"
# Tool to format memory cards complying with the SD File System spec
cask "sdformatter"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# Replacement for RCDefaultApps, written in Swift
cask "swiftdefaultappsprefpane"
# Messaging app with a focus on speed and security
cask "telegram"
# Virtual machines UI using QEMU
cask "utm"
# Custom Discord App
cask "vesktop"
# Wine wrapper built with SwiftUI
cask "whisky"
# Lossless audio decoder
cask "thedavidweng/unsigned-tap/xld", trusted: true
# Collect, organise, cite, and share research sources
cask "zotero"
mas "Accelerate", id: 1459809092
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "CrystalFetch", id: 6454431289
mas "DaisyDisk", id: 411643860
mas "Goodnotes", id: 1444383602
mas "Mactracker", id: 430255202
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "PiPifier", id: 1160374471
mas "Refined GitHub", id: 1519867270
mas "Select Like A Boss For Safari", id: 1437310115
mas "Tampermonkey", id: 6738342400
mas "TestFlight", id: 899247664
mas "uBlock Origin Lite", id: 6745342698
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
