tap "brewforge/chinese", trusted: true
tap "dmmulroy/tap"
tap "gromgit/fuse", trusted: true
tap "homebrew-ffmpeg/ffmpeg", trusted: true
tap "homebrew/services"
tap "iohannrabeson/tap", "https://github.com/IohannRabeson/homebrew-tap"
tap "laishulu/homebrew", trusted: true
tap "libkrun/krun", "https://github.com/libkrun/homebrew-krun.git", trusted: true
tap "louisbrunner/valgrind", trusted: true
tap "nikitabobko/tap", trusted: true
tap "rami3l/tap", trusted: true
tap "syhily/git-gc", trusted: true
tap "thedavidweng/unsigned-tap"
# Generate compilation database for clang tooling
brew "bear"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Easily generate Instruments traces for your rust crate
brew "cargo-instruments"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Isolated development environments using Docker
brew "docker-compose"
# Functional metaprogramming aware language built on Erlang VM
brew "elixir"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Installer for the general purpose language Haskell
brew "ghcup"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Library access to GnuPG
brew "gpgme"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Modern format for Haskell packages
brew "hpack"
# Simple terminal UI for git commands
brew "lazygit"
# Development kit for the Java programming language
brew "openjdk"
# Build tool for Clojure
brew "leiningen"
# Version of the SSL/TLS protocol forked from OpenSSL
brew "libressl"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Package manager for the Lua programming language
brew "luarocks"
# Java-based project management
brew "maven"
# Minimalist GNU for Windows and GCC cross-compilers
brew "mingw-w64"
# High dynamic-range image file format
brew "openexr"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Pandoc filter for numbering and cross-referencing
brew "pandoc-crossref"
# Sliding, tiling window manager for MacOS
brew "paneru"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Fast, disk space efficient package manager
brew "pnpm"
# Tool for managing OCI containers and pods
brew "podman"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Hook preloader
brew "proxychains-ng"
# Advanced Python REPL
brew "ptpython"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Generic machine emulator and virtualizer
brew "qemu"
# SVG rendering tool and library
brew "resvg"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
brew "rustup", args: ["HEAD"]
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Makes Time Machine respect .gitignore files
brew "iohannrabeson/tap/tmignore-rs", trusted: true
# CLI tool to start Linux KVM or macOS HVF VMs using the libkrun
brew "libkrun/krun/krunkit"
# Dynamic analysis tools (memory, debug, profiling)
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"], trusted: true
# An input source switching daemon for macOS.
brew "rami3l/tap/clavy", args: ["HEAD"]
# Pacman-like syntax wrapper for many package managers.
brew "rami3l/tap/pacaptr", args: ["HEAD"]
# Yet another tcping.
brew "rami3l/tap/ting"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Android SDK component
cask "android-platform-tools"
# Display management tool
cask "betterdisplay"
# Tool to customise input devices and automate computer systems
cask "bettertouchtool"
# Server and cloud storage browser
cask "cyberduck"
# Advanced Dock preferences
cask "dockey"
# Matrix collaboration client
cask "element"
cask "font-0xproto-nerd-font"
cask "font-agave"
cask "rami3l/tap/font-anka-coder-narrow"
cask "font-barlow"
cask "font-camingocode"
cask "font-cascadia-code-nf"
cask "font-commit-mono"
cask "font-cormorant-garamond"
cask "font-d2coding-nerd-font"
cask "font-dejavu"
cask "rami3l/tap/font-dseg"
cask "font-eb-garamond"
cask "font-fantasque-sans-mono"
cask "font-fira-code"
cask "font-fragment-mono"
cask "font-hackgen-nerd"
cask "font-ia-writer-mono"
cask "font-ibm-plex-sans"
cask "font-ibm-plex-serif"
cask "font-inconsolata-nerd-font"
cask "font-input"
cask "font-inter"
cask "font-iosevka"
cask "font-iosevka-slab"
cask "font-jetbrains-mono"
cask "font-juisee-nf"
cask "font-latin-modern"
cask "font-latin-modern-math"
cask "font-league-mono"
cask "font-lxgw-bright"
cask "font-m-plus-code-latin"
cask "font-maple-mono"
cask "font-merriweather"
cask "font-monaspace"
cask "font-mononoki-nerd-font"
cask "font-moralerspace-hw"
cask "font-noto-nerd-font"
cask "font-noto-sans"
cask "font-noto-sans-cjk"
cask "font-noto-sans-mono"
cask "font-noto-serif"
cask "font-noto-serif-cjk"
cask "font-oxygen-mono"
cask "font-photonico-code"
cask "font-pixel-code"
cask "font-plemol-jp-nf"
cask "font-recursive"
cask "font-recursive-code"
cask "font-roboto"
cask "font-roboto-flex"
cask "font-roboto-mono-nerd-font"
cask "font-roboto-slab"
cask "font-source-code-pro"
cask "font-sudo"
cask "font-symbols-only-nerd-font"
cask "font-terminess-ttf-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "font-udev-gothic-nf"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Tools to protect your emails and files
cask "gpg-suite"
# Free and open-source media player
cask "iina"
# Keyboard customiser
cask "karabiner-elements"
# File archiver
cask "keka"
# Free and open-source media player
cask "kodi"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Open-source download manager
cask "motrix"
# Mounts servers and cloud storages as a disk on the desktop
cask "mountain-duck"
# Re-mounts write-protected NTFS volumes
cask "mounty"
# Free and open-source RSS reader
cask "netnewswire"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Android file transfer
cask "openmtp"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
# Colour picker for colours onscreen
cask "pika"
# Browse, manage, inspect containers and images
cask "podman-desktop"
# Peer to peer Bitorrent client
cask "thedavidweng/unsigned-tap/qbittorrent", trusted: true
# HTTP client that helps testing and describing APIs
cask "rapidapi"
# Tool to format memory cards complying with the SD File System spec
cask "sdformatter"
# Video game digital distribution service
cask "steam"
# Replacement for RCDefaultApps, written in Swift
cask "swiftdefaultappsprefpane"
# Messaging app with a focus on speed and security
cask "telegram"
# Virtual machines UI using QEMU
cask "utm"
# Custom Discord App
cask "vesktop"
# Wine wrapper built with SwiftUI
cask "whisky"
# Network protocol analyzer
cask "wireshark-app"
# Lossless audio decoder
cask "thedavidweng/unsigned-tap/xld", trusted: true
# Collect, organise, cite, and share research sources
cask "zotero"
mas "Accelerate", id: 1459809092
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "CrystalFetch", id: 6454431289
mas "DaisyDisk", id: 411643860
mas "Goodnotes", id: 1444383602
mas "iStat Menus", id: 1319778037
mas "Mactracker", id: 430255202
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "PiPifier", id: 1160374471
mas "Refined GitHub", id: 1519867270
mas "Select Like A Boss For Safari", id: 1437310115
mas "Tampermonkey", id: 6738342400
mas "TestFlight", id: 899247664
mas "uBlock Origin Lite", id: 6745342698
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
go "github.com/air-verse/air"
go "github.com/loov/goda"
cargo "cargo-valgrind"
cargo "dioxus-cli"
cargo "kache"
